//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2021.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2021.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 190
        ///168
        ///166
        ///163
        ///170
        ///160
        ///171
        ///166
        ///161
        ///167
        ///175
        ///178
        ///193
        ///189
        ///188
        ///191
        ///193
        ///192
        ///193
        ///180
        ///177
        ///178
        ///176
        ///177
        ///196
        ///203
        ///211
        ///209
        ///210
        ///209
        ///225
        ///219
        ///229
        ///214
        ///202
        ///205
        ///208
        ///207
        ///208
        ///204
        ///208
        ///206
        ///205
        ///208
        ///209
        ///219
        ///236
        ///241
        ///243
        ///239
        ///251
        ///278
        ///279
        ///284
        ///283
        ///287
        ///244
        ///245
        ///257
        ///253
        ///272
        ///276
        ///287
        ///288
        ///304
        ///306
        ///313
        ///312
        ///284
        ///293
        ///288
        ///289
        ///290
        ///283
        ///298
        ///309
        ///300
        ///298
        ///297
        ///291
        ///292
        ///304
        ///301
        ///303
        ///306
        ///280
        ///286
        ///266
        ///270
        ///272
        ///274
        ///269
        ///270
        ///271
        ///270
        ///266
        ///274
        ///275
        ///278
        ///280
        ///283
        ///284
        ///28 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&lt;&lt;{[{([([({&lt;{&lt;&gt;{}}&gt;[[[]{}][[]&lt;&gt;])}{[(())][[&lt;&gt;{}]{[]{}}]})](([{&lt;&lt;&gt;{}&gt;[()&lt;&gt;]}&lt;&lt;&lt;&gt;()&gt;{{}&lt;&gt;}&gt;]{[{{}()}[(){}]]})
        ///[({[[(&lt;{[&lt;[&lt;{({}[])(&lt;&gt;{})}(([]&lt;&gt;)[[]()])&gt;{[&lt;{}()&gt;&lt;{}{}&gt;][&lt;[]()&gt;({}())]}]&lt;(&lt;(()&lt;&gt;){{}{}}&gt;({()()}(()[])))&gt;&gt;[([
        ///(&lt;([[&lt;(&lt;&lt;{((&lt;&lt;&lt;&gt;{}&gt;{{}{}}&gt;({()&lt;&gt;}{()&lt;&gt;}))&lt;[(&lt;&gt;&lt;&gt;)&lt;&lt;&gt;()&gt;]{((){}){[]&lt;&gt;}}&gt;)}({&lt;[(()[]){()[]}]{((
        ///&lt;[(&lt;{[{{([([{{{}&lt;&gt;}}{{&lt;&gt;()}&lt;&lt;&gt;&gt;}]){[[&lt;[]&lt;&gt;&gt;(())]&lt;&lt;&lt;&gt;{}&gt;(())&gt;][&lt;&lt;{}{}&gt;(&lt;&gt;())&gt;{&lt;{}{}&gt;&lt;{}&lt;&gt;&gt;}]}]&lt;&lt;({{()
        ///{(((&lt;{{{&lt;&lt;{({{()[]){()[]}}({{}}[&lt;&gt;[]])){[{()&lt;&gt;}&lt;()()&gt;]}}&gt;{[[{&lt;[]{}&gt;{{}()}}&lt;&lt;()[]&gt;[{}[]]&gt;]{[{(){ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day10 {
            get {
                return ResourceManager.GetString("Day10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [({(&lt;(())[]&gt;[[{[]{&lt;()&lt;&gt;&gt;
        ///[(()[&lt;&gt;])]({[&lt;{&lt;&lt;[]&gt;&gt;(
        ///{([(&lt;{}[&lt;&gt;[]}&gt;{[]{[(&lt;()&gt;
        ///(((({&lt;&gt;}&lt;{&lt;{&lt;&gt;}{[]{[]{}
        ///[[&lt;[([]))&lt;([[{}[[()]]]
        ///[{[{({}]{}}([{[{{{}}([]
        ///{&lt;[[]]&gt;}&lt;{[{[{[]{()[[[]
        ///[&lt;(&lt;(&lt;(&lt;{}))&gt;&lt;([]([]()
        ///&lt;{([([[(&lt;&gt;()){}]&gt;(&lt;&lt;{{
        ///&lt;{([{{}}[&lt;[[[&lt;&gt;{}]]]&gt;[]].
        /// </summary>
        internal static string Day10_Debug {
            get {
                return ResourceManager.GetString("Day10_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1564524226
        ///1384554685
        ///7582264835
        ///8812672272
        ///1161463137
        ///7831762344
        ///2855527748
        ///6141737874
        ///8611458313
        ///8215372443.
        /// </summary>
        internal static string Day11 {
            get {
                return ResourceManager.GetString("Day11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5483143223
        ///2745854711
        ///5264556173
        ///6141336146
        ///6357385478
        ///4167524645
        ///2176841721
        ///6882881134
        ///4846848554
        ///5283751526.
        /// </summary>
        internal static string Day11_Debug {
            get {
                return ResourceManager.GetString("Day11_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start-A
        ///start-b
        ///A-c
        ///A-b
        ///b-d
        ///A-end
        ///b-end.
        /// </summary>
        internal static string Day12_Debug {
            get {
                return ResourceManager.GetString("Day12_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 323,305
        ///512,845
        ///780,175
        ///308,50
        ///266,604
        ///152,425
        ///199,618
        ///214,572
        ///977,596
        ///1113,756
        ///1019,316
        ///972,322
        ///1181,138
        ///785,756
        ///504,378
        ///597,537
        ///1068,485
        ///738,108
        ///437,359
        ///1163,567
        ///585,549
        ///490,527
        ///616,5
        ///258,605
        ///1265,473
        ///728,421
        ///659,626
        ///162,781
        ///725,549
        ///165,23
        ///1148,554
        ///169,710
        ///388,290
        ///989,746
        ///619,361
        ///951,850
        ///1136,770
        ///592,284
        ///298,430
        ///441,408
        ///1014,534
        ///147,77
        ///822,429
        ///1210,162
        ///109,647
        ///65,605
        ///319,595
        ///535,315
        ///691,420
        ///266,290
        ///127,824
        ///435,779
        ///306,161
        ///248,653
        ///23,478
        ///751,276
        ///1295, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day13 {
            get {
                return ResourceManager.GetString("Day13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6,10
        ///0,14
        ///9,10
        ///0,3
        ///10,4
        ///4,11
        ///6,0
        ///6,12
        ///4,1
        ///0,13
        ///10,12
        ///3,4
        ///3,0
        ///8,4
        ///1,10
        ///2,14
        ///8,10
        ///9,0
        ///
        ///fold along y=7
        ///fold along x=5.
        /// </summary>
        internal static string Day13_Debug {
            get {
                return ResourceManager.GetString("Day13_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forward 5
        ///forward 2
        ///forward 9
        ///down 2
        ///forward 9
        ///forward 3
        ///forward 2
        ///down 6
        ///forward 3
        ///forward 3
        ///down 3
        ///down 3
        ///forward 8
        ///down 5
        ///forward 7
        ///forward 9
        ///forward 9
        ///forward 6
        ///forward 9
        ///forward 3
        ///forward 3
        ///forward 1
        ///forward 7
        ///down 6
        ///forward 7
        ///forward 4
        ///down 3
        ///down 1
        ///forward 4
        ///down 7
        ///down 2
        ///down 8
        ///forward 9
        ///down 5
        ///down 2
        ///forward 6
        ///up 4
        ///down 3
        ///down 1
        ///down 6
        ///down 7
        ///forward 6
        ///up 2
        ///forward 2
        ///down 9
        ///down 3
        ///forward 7
        ///up 3
        ///up 7
        ///forward 8
        ///forward 7
        ///down 4
        ///up 8
        ///up 1
        ///forward  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 011010010110
        ///101110100110
        ///011011011110
        ///100011010001
        ///011011100111
        ///011000100101
        ///101101011001
        ///010001001001
        ///100010110111
        ///001110110101
        ///100111011001
        ///100110111011
        ///000000111101
        ///000000011101
        ///011101000011
        ///101101001111
        ///110101011101
        ///010100000100
        ///100111010001
        ///111110001000
        ///000110110110
        ///001001101101
        ///001110110111
        ///101110110101
        ///010001111000
        ///111101010111
        ///110011101110
        ///010111011100
        ///100101011111
        ///111011011011
        ///100110100111
        ///001000101010
        ///101000010000
        ///101010000111
        ///000100100101
        ///111111111101
        ///00010010 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42,32,13,22,91,2,88,85,53,87,37,33,76,98,89,19,69,9,62,21,38,49,54,81,0,26,79,36,57,18,4,40,31,80,24,64,77,97,70,6,73,23,20,47,45,51,74,25,95,96,58,92,94,11,39,63,65,99,48,83,29,34,44,75,55,17,14,56,8,82,59,52,46,90,5,41,60,67,16,1,15,61,71,66,72,30,28,3,43,27,78,10,86,7,50,35,84,12,93,68
        ///
        ///90  8  2 34 41
        ///11 67 74 71 62
        ///47 42 44  1 17
        ///21 55 12 91  6
        ///60 69 75 92 56
        ///
        ///49 29 60 45 31
        ///94 51 73 33 67
        ///21 92 53 95 96
        /// 2 55 52  8 87
        /// 4 36 76 83 42
        ///
        ///23 66 50 84 58
        ///62 98 81 76 57
        ///24  2 56 79  6
        ///55  0 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 510,771 -&gt; 510,322
        ///753,99 -&gt; 753,280
        ///160,330 -&gt; 33,330
        ///700,793 -&gt; 700,892
        ///327,168 -&gt; 327,690
        ///264,203 -&gt; 264,839
        ///135,134 -&gt; 314,134
        ///209,759 -&gt; 41,759
        ///474,514 -&gt; 491,531
        ///977,988 -&gt; 42,53
        ///924,245 -&gt; 278,891
        ///466,952 -&gt; 466,135
        ///381,560 -&gt; 822,119
        ///339,828 -&gt; 339,730
        ///114,775 -&gt; 114,508
        ///472,44 -&gt; 472,32
        ///815,512 -&gt; 188,512
        ///516,579 -&gt; 987,108
        ///219,386 -&gt; 219,838
        ///456,592 -&gt; 456,496
        ///778,300 -&gt; 355,300
        ///277,27 -&gt; 69,27
        ///889,217 -&gt; 307,799
        ///470,471 -&gt; 249,471
        ///655,867 -&gt; 20,232
        ///845,623 -&gt; 675,623
        ///278 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day5 {
            get {
                return ResourceManager.GetString("Day5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,1,5,2,1,1,5,5,3,1,1,1,1,1,1,3,4,5,2,1,2,1,1,1,1,1,1,1,1,3,1,1,5,4,5,1,5,3,1,3,2,1,1,1,1,2,4,1,5,1,1,1,4,4,1,1,1,1,1,1,3,4,5,1,1,2,1,1,5,1,1,4,1,4,4,2,4,4,2,2,1,2,3,1,1,2,5,3,1,1,1,4,1,2,2,1,4,1,1,2,5,1,3,2,5,2,5,1,1,1,5,3,1,3,1,5,3,3,4,1,1,4,4,1,3,3,2,5,5,1,1,1,1,3,1,5,2,1,3,5,1,4,3,1,3,1,1,3,1,1,1,1,1,1,5,1,1,5,5,2,1,5,1,4,1,1,5,1,1,1,5,5,5,1,4,5,1,3,1,2,5,1,1,1,5,1,1,4,1,1,2,3,1,3,4,1,2,1,4,3,1,2,4,1,5,1,1,1,1,1,3,4,1,1,5,1,1,3,1,1,2,1,3,1,2,1,1,3,3,4,5,3,5,1,1,1,1,1,1,1,1,1,5,4,1,5,1,3,1,1,2,5,1,1,4,1, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day6 {
            get {
                return ResourceManager.GetString("Day6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1101,1,29,67,1102,0,1,65,1008,65,35,66,1005,66,28,1,67,65,20,4,0,1001,65,1,65,1106,0,8,99,35,67,101,99,105,32,110,39,101,115,116,32,112,97,115,32,117,110,101,32,105,110,116,99,111,100,101,32,112,114,111,103,114,97,109,10,161,185,311,752,668,728,210,741,636,381,1222,509,282,156,806,624,31,300,711,128,146,368,306,239,7,519,441,368,179,155,704,274,237,710,164,55,217,1007,0,701,812,713,127,536,320,163,454,310,726,433,426,102,1350,736,408,951,307,15,333,462,755,797,265,540,680,357,914,195,468,1034,583,413,1293,4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day7 {
            get {
                return ResourceManager.GetString("Day7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fdaebc egc gc bgefc ecbagd becfa fagc afgbec gdcbfae bgdef | cgfa gcebad ebcadfg cefgbad
        ///dbafgec ce cgefdb abged aedc bec deafgb cbage edgbac gfacb | abcfg edca febdcg ecb
        ///cad dgec fbdea bfgcad efabgc gacedf cfgae cd cdefa dbceagf | adefb aebfd aecbfg cedfa
        ///ebaf fa abfcd cbfde egbfcad gdbac cabfed gedcfb gafedc adf | fgdbcae dabfc aedcbf af
        ///decfag ca bdfag afc edca fdbceg dfgac cabfge gcdef cbfgdea | bafceg dagfc bacfdge fdgab
        ///gcedf bdgafe gbadec bgc cfab bc gcfdb dbfag facbegd fagbcd | dbfcgea dgfbca  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day8 {
            get {
                return ResourceManager.GetString("Day8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9987653234589654549865432101235789979765459832101234567943986543101239874321012932397319985214896543
        ///9898541015678943239876973876545699868954398765212345678932399654592345965432129891985498764323789432
        ///9765432126789654123998765987897789759893219894333656789543498986989957898543498789976579895454678943
        ///9879656737899797434589986798998897646789398989454789898959987899876899987654989678899699976565789656
        ///8998767945678996545678997999569965435678987678967897947898765698765678998799878466798989988676898777
        ///76 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day9 {
            get {
                return ResourceManager.GetString("Day9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2199943210
        ///3987894921
        ///9856789892
        ///8767896789
        ///9899965678.
        /// </summary>
        internal static string Day9_Debug {
            get {
                return ResourceManager.GetString("Day9_Debug", resourceCulture);
            }
        }
    }
}
