//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2021.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2021.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 190
        ///168
        ///166
        ///163
        ///170
        ///160
        ///171
        ///166
        ///161
        ///167
        ///175
        ///178
        ///193
        ///189
        ///188
        ///191
        ///193
        ///192
        ///193
        ///180
        ///177
        ///178
        ///176
        ///177
        ///196
        ///203
        ///211
        ///209
        ///210
        ///209
        ///225
        ///219
        ///229
        ///214
        ///202
        ///205
        ///208
        ///207
        ///208
        ///204
        ///208
        ///206
        ///205
        ///208
        ///209
        ///219
        ///236
        ///241
        ///243
        ///239
        ///251
        ///278
        ///279
        ///284
        ///283
        ///287
        ///244
        ///245
        ///257
        ///253
        ///272
        ///276
        ///287
        ///288
        ///304
        ///306
        ///313
        ///312
        ///284
        ///293
        ///288
        ///289
        ///290
        ///283
        ///298
        ///309
        ///300
        ///298
        ///297
        ///291
        ///292
        ///304
        ///301
        ///303
        ///306
        ///280
        ///286
        ///266
        ///270
        ///272
        ///274
        ///269
        ///270
        ///271
        ///270
        ///266
        ///274
        ///275
        ///278
        ///280
        ///283
        ///284
        ///28 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1_Part1 {
            get {
                return ResourceManager.GetString("Day1_Part1", resourceCulture);
            }
        }
    }
}
